FROM python:3.9

# WORKDIR /appp
WORKDIR /app

# COPY appy.py /app
COPY app.py /app

# RUN pip install flask netiface
RUN pip install flask netifaces

# EXPOSE "eight thousand"
EXPOSE 8000

# CMD ["pythn", "app.py"]
CMD ["python", "app.py"]

